# Generated by Django 5.2 on 2025-05-05 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('GRAU', 'Óculos de Grau'), ('SOL', 'Óculos de Sol'), ('LENTES', 'Lentes de Contato'), ('ACESSORIOS', 'Acessórios'), ('SAUDE', 'Saúde Ocular'), ('INFANTIL', 'Óculos Infantis'), ('ESPORTE', 'Óculos Esportivos')], help_text='Este campo é obrigatório', max_length=100, unique=True)),
            ],
        ),
    ]
