# Generated by Django 5.2 on 2025-05-05 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0003_popular_categorias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorias',
            name='nome',
            field=models.CharField(choices=[('GRAU', 'Óculos de Grau'), ('SOL', 'Óculos de Sol'), ('LENTES', 'Lentes de Contato'), ('ACESSORIOS', 'Acessórios'), ('SAUDE', 'Saúde Ocular'), ('INFANTIL', 'Óculos Infantis'), ('ESPORTE', 'Óculos Esportivos')], help_text='Este campo é obrigatório', max_length=100, unique=True),
        ),
    ]
