# Generated by Django 5.2 on 2025-06-18 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0002_alter_fornecedor_descricao_alter_fornecedor_endereco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='contato',
            field=models.CharField(max_length=100, unique=True, verbose_name='Contato'),
        ),
    ]
