# Generated by Django 5.2 on 2025-05-06 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marca', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marca',
            name='nome',
            field=models.CharField(error_messages={'unique': 'Já existe uma marca com este nome'}, help_text='Este campo é obrigatório', max_length=50, unique=True),
        ),
    ]
