# Generated by Django 5.2 on 2025-06-28 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marca', '0002_alter_marca_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marca',
            name='nome',
            field=models.CharField(error_messages={'required': 'Este campo é obrigatório', 'unique': 'Já existe uma marca com este nome'}, help_text='Este campo é obrigatório', max_length=50, unique=True),
        ),
    ]
