# Generated by Django 5.2 on 2025-05-05 23:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Campo obrigatório', max_length=255, verbose_name='Nome do Funcionário')),
                ('cargo', models.CharField(help_text='Campo obrigatório', max_length=255, verbose_name='Cargo')),
                ('telefone', models.CharField(help_text='Campo obrigatório', max_length=11, validators=[django.core.validators.RegexValidator('^\\d{11}$', 'O número de telefone deve ter 11 dígitos númericos')], verbose_name='Telefone')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
                'ordering': ['nome'],
            },
        ),
    ]
