# Generated by Django 5.2 on 2025-06-13 18:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='nome',
            field=models.CharField(help_text='Campo obrigatório', max_length=255, unique=True, verbose_name='Nome do Funcionário'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='telefone',
            field=models.CharField(help_text='Campo obrigatório', max_length=11, unique=True, validators=[django.core.validators.RegexValidator('^\\d{11}$', 'O número de telefone deve ter 11 dígitos numéricos')], verbose_name='Telefone'),
        ),
    ]
