# Generated by Django 5.2 on 2025-06-22 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcao', '0002_alter_funcao_nome_alter_funcao_salario'),
        ('funcionarios', '0002_alter_funcionario_nome_alter_funcionario_telefone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='cargo',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='funcao',
            field=models.ForeignKey(default=1, help_text='Campo obrigatório', on_delete=django.db.models.deletion.PROTECT, to='funcao.funcao', verbose_name='Função'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='nome',
            field=models.CharField(help_text='Campo obrigatório', max_length=255, verbose_name='Nome do Funcionário'),
        ),
    ]
