# Generated by Django 5.2 on 2025-06-19 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Campo obrigatório', max_length=255, unique=True, verbose_name='Nome da Função')),
                ('salario', models.DecimalField(decimal_places=2, help_text='Campo obrigatório', max_digits=10, verbose_name='Salário')),
            ],
            options={
                'verbose_name': 'Função',
                'verbose_name_plural': 'Funções',
                'ordering': ['nome'],
            },
        ),
    ]
