# Generated by Django 5.2 on 2025-06-22 00:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcao',
            name='nome',
            field=models.CharField(help_text='Campo obrigatório', max_length=255, unique=True, validators=[django.core.validators.RegexValidator(message='O nome da função deve conter apenas letras e espaços.', regex='^[a-zA-Z\\s]+$')], verbose_name='Nome da Função'),
        ),
        migrations.AlterField(
            model_name='funcao',
            name='salario',
            field=models.DecimalField(decimal_places=2, help_text='Campo obrigatório', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01, message='O salário deve ser maior que zero.')], verbose_name='Salário'),
        ),
    ]
