# Generated by Django 5.2 on 2025-07-15 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0002_alter_cliente_options'),
        ('entrada', '0003_alter_entrada_fornecedor_alter_entrada_quantidade_and_more'),
        ('funcionarios', '0003_remove_funcionario_cargo_funcionario_funcao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cliente.cliente')),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entrada.entrada')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='funcionarios.funcionario')),
            ],
        ),
    ]
