# Generated by Django 5.2 on 2025-07-15 18:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='preco',
            field=models.FloatField(default=100, validators=[django.core.validators.MinValueValidator(1.0)]),
            preserve_default=False,
        ),
    ]
