# Generated by Django 5.2 on 2025-05-05 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default=1, error_messages={'unique': 'Já existe um modelo com este nome'}, max_length=100, unique=True)),
                ('marca', models.CharField(max_length=100)),
            ],
        ),
    ]
