# Generated by Django 5.2 on 2025-05-05 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelo',
            name='nome',
            field=models.CharField(default=1, error_messages={'unique': 'Já existe um modelo com este nome'}, max_length=100, unique=True),
        ),
    ]
