# Generated by Django 5.2 on 2025-05-06 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marca', '0002_alter_marca_nome'),
        ('modelo', '0002_alter_modelo_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelo',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marca.marca'),
        ),
    ]
