# Generated by Django 5.2 on 2025-05-05 20:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0001_initial'),
        ('modelo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Este campo é obrigatório', max_length=100)),
                ('preco', models.FloatField(help_text='Insira o valor do produto', validators=[django.core.validators.MinValueValidator(1.0)])),
                ('quantidade', models.PositiveIntegerField(help_text='Insira a quantidade.', validators=[django.core.validators.MinValueValidator(1)])),
                ('cor', models.CharField(max_length=30)),
                ('tamanho', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)])),
                ('marca', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=1000)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='categorias.categorias')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='modelo.modelo')),
            ],
        ),
    ]
