# Generated by Django 5.2 on 2025-04-10 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Este campo é obrigatório', max_length=100)),
                ('preco', models.FloatField(help_text='Insira o valor do produto')),
                ('quantidade', models.IntegerField(help_text='Insira a quantidade.')),
                ('cor', models.CharField(max_length=30)),
                ('tamanho', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=1000)),
                ('marca', models.CharField(max_length=100)),
            ],
        ),
    ]
