# Generated by Django 5.2 on 2025-06-28 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0003_alter_fornecedor_contato'),
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtos',
            name='preco',
        ),
        migrations.RemoveField(
            model_name='produtos',
            name='quantidade',
        ),
        migrations.AddField(
            model_name='produtos',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fornecedores.fornecedor'),
        ),
    ]
