# Generated by Django 5.2 on 2025-04-14 21:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='categorias.categorias'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produtos',
            name='preco',
            field=models.FloatField(help_text='Insira o valor do produto', validators=[django.core.validators.MinValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='quantidade',
            field=models.IntegerField(help_text='Insira a quantidade.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='tamanho',
            field=models.FloatField(max_length=100, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
