# Generated by Django 5.2 on 2025-07-15 19:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_remove_produtos_preco_remove_produtos_quantidade_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produtos',
            options={'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
        migrations.RemoveField(
            model_name='produtos',
            name='fornecedor',
        ),
        migrations.AddField(
            model_name='produtos',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='produtos',
            name='quantidade',
            field=models.PositiveIntegerField(default=1, help_text='Insira a quantidade.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
