# Generated by Django 5.2 on 2025-04-28 20:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_produtos_categoria_alter_produtos_preco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='quantidade',
            field=models.PositiveIntegerField(help_text='Insira a quantidade.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
