# Generated by Django 5.2 on 2025-04-28 20:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0001_initial'),
        ('produtos', '0003_alter_produtos_quantidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='modelo',
            field=models.ForeignKey(default='modelo_padrao', on_delete=django.db.models.deletion.PROTECT, to='modelo.modelo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produtos',
            name='tamanho',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
