# Generated by Django 5.2 on 2025-05-22 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrada', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='data_entrada',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
