# Generated by Django 5.2 on 2025-07-15 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0003_remove_funcionario_cargo_funcionario_funcao_and_more'),
        ('produtos', '0003_alter_produtos_options_remove_produtos_fornecedor_and_more'),
        ('vendas', '0003_alter_venda_options_alter_venda_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='funcionario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendas_funcionario', to='funcionarios.funcionario'),
        ),
        migrations.AddField(
            model_name='venda',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendas_produto', to='produtos.produtos'),
        ),
    ]
