# Generated by Django 5.2 on 2025-10-20 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_alter_produtos_options_remove_produtos_fornecedor_and_more'),
        ('vendas', '0004_venda_funcionario_venda_produto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='produto',
        ),
        migrations.AddField(
            model_name='venda',
            name='itens',
            field=models.ManyToManyField(related_name='vendas_produtos', to='produtos.produtos'),
        ),
    ]
