# Generated by Django 5.2 on 2025-10-21 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_alter_produtos_options_remove_produtos_fornecedor_and_more'),
        ('vendas', '0005_remove_venda_produto_venda_itens'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venda',
            options={},
        ),
        migrations.RemoveField(
            model_name='venda',
            name='itens',
        ),
        migrations.CreateModel(
            name='ItemVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.produtos')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_venda', to='vendas.venda')),
            ],
        ),
    ]
