# Generated by Django 5.2 on 2025-10-21 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0006_alter_venda_options_remove_venda_itens_itemvenda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
